// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"jti-test-backend/app"
	"jti-test-backend/controller"
	"jti-test-backend/middleware"
	"jti-test-backend/repository"
	"jti-test-backend/service"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	phoneNumberRepositoryImpl := repository.NewPhoneNumberRepositoryImpl()
	db := app.GetConnection()
	validate := validator.New()
	phoneNumberServiceImpl := service.NewPhoneNumberServiceImpl(phoneNumberRepositoryImpl, db, validate)
	phoneNumberControllerImpl := controller.NewPhoneNumberControllerImpl(phoneNumberServiceImpl)
	router := app.NewRouter(phoneNumberControllerImpl)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := NewServer(authMiddleware)
	return server
}

// injector.go:

var phoneNumberSet = wire.NewSet(repository.NewPhoneNumberRepositoryImpl, wire.Bind(new(repository.PhoneNumberRepository), new(*repository.PhoneNumberRepositoryImpl)), service.NewPhoneNumberServiceImpl, wire.Bind(new(service.PhoneNumberService), new(*service.PhoneNumberServiceImpl)), controller.NewPhoneNumberControllerImpl, wire.Bind(new(controller.PhoneNumberController), new(*controller.PhoneNumberControllerImpl)))
